name: Build SDK

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      rome_evm_branch:
        description: 'Branch name for the rome-evm repository'
        required: false
        default: 'main'
env:
  REF_NAME: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev
      - name: Checkout code
        uses: actions/checkout@master
        with:
          path: rome-sdk
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Determine EVM branch name'
        id: get_branch_name
        run: |
          # If it's a workflow_dispatch, use the provided branch name
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            EVM_BRANCH_NAME="${{ github.event.inputs.rome_evm_branch }}"
          else
            EVM_BRANCH_NAME="main"
          fi
          echo "evm_branch_name=$EVM_BRANCH_NAME" >> $GITHUB_ENV

      - name: 'Checkout EVM repository'
        uses: actions/checkout@master
        with:
          repository: rome-labs/rome-evm
          path: rome-evm
          ref: ${{ env.evm_branch_name }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Build rome-sdk'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          file: rome-sdk/Dockerfile
