name: Build and Deploy RustDoc to S3

on: workflow_dispatch

env:
  REF_NAME: ${{github.ref_name}}
  ROME_EVM_REF_NAME: master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: 'us-east-1'  # Set your AWS region here
      SOLANA_VERSION: 1.18.17

    steps:
    - name: 'Checkout rome-sdk reposotory'
      uses: actions/checkout@master
      with:
        path: rome-sdk
        repository: rome-labs/rome-sdk
        ref: ${{env.REF_NAME}}
        token: ${{secrets.GIT_ROLLUP_TOKEN}}

    - name: 'Checkout rome-evm reposotory'
      uses: actions/checkout@master
      with:
        path: rome-evm
        repository: rome-labs/rome-evm
        ref: ${{env.ROME_EVM_REF_NAME}}
        token: ${{secrets.GIT_ROLLUP_TOKEN}}

    - name: 'Checkout Rome Scripts reposotory'
      uses: actions/checkout@master
      with:
        path: rome-scripts
        repository: rome-labs/rome-scripts
        token: ${{ secrets.GIT_ROLLUP_TOKEN }}

    - name: 'Checkout Rome Program reposotory'
      uses: actions/checkout@master
      with:
        path: rome-rollup-program
        repository: rome-labs/rome-rollup-program
        token: ${{ secrets.GIT_ROLLUP_TOKEN }}

    - name: Install Solana
      uses: metadaoproject/setup-solana@v1.0
      with:
        solana-cli-version: $SOLANA_VERSION

    - name: add solana to git path
      run: echo "/root/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
    - name: Print path
      run: echo $PATH
    - name: Check Solana version
      run: solana --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::878555667898:role/github-actions-role
        role-session-name: GitHubActionsRomeMVP

    - name: Install AWS CLI
      run: sudo apt-get update && sudo apt-get install awscli -y

    - name : Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "25.x"

    - name: Check Protocol Buffers
      run: |
        protoc --version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Create config file using rome scripts
      run: |
        cd rome-scripts
        make CHAIN_ID=2 ROLLUP_NAME="rollup2" SOLANA_URL="http://localhost:8899" NEON_REVISION="latest" config

    - name: Build Rome SDK and Docs
      run: |
        cd rome-sdk
        make build
        make lint
        make doc

    - name: Upload Doc to S3
      run: |
        cd rome-sdk
        aws s3 sync ./target/doc s3://docs.devnet.romeprotocol.xyz/
